name: park_it
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.18.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_native_splash: ^2.2.15
  flutter_launcher_icons: ^0.11.0
  firebase_core: ^2.3.0
  firebase_auth: ^4.1.3
  firebase_storage: ^11.0.6
  email_validator: ^2.0.1
  custom_navigation_bar: ^0.8.2
  shared_preferences: ^2.0.15
  cloud_firestore: ^4.1.0
  date_time_picker: ^2.1.0
  provider: ^6.0.4
  numberpicker: ^2.1.1

flutter_native_splash:
  color: "#ED6560"
  image: assets/3x.png
  android: true
  ios: true
  android_gravity: fill
  ios_content_mode: scaleAspectFill

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/group.png"
  min_sdk_android: 21

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
